name: apieliminatorias pipeline
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL_PROD: jdbc:postgresql://dpg-cqf839ogph6c73b96o8g-a.ohio-postgres.render.com/eliminatoriasdb
      DB_USER_PROD: luisivill
      DB_PASS_PROD: JAbTXAOF1h6Nb0t4js0LTLAuRnTsCWjl
    steps:
      - name: Environment
        run: |
          echo "DB_URL_PROD=$DB_URL_PROD"
          echo "DB_USER_PROD=$DB_USER_PROD"
          echo "DB_PASS_PROD=$DB_PASS_PROD"
          printenv | grep DB_URL_PROD
          printenv | grep DB_USER_PROD
          printenv | grep DB_PASS_PROD

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven build
        run: mvn --batch-mode --update-snapshots clean package

      - name: List build directory
        run: ls -la target
