name: apieliminatorias pipeline
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'
          cache: maven

      - name: Maven build
        run: mvn --batch-mode --update-snapshots clean package

      - name: List build directory
        run: ls -la target
