name: apieliminatorias pipeline
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up java 17 y maven
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt-openjdk'
          maven-version: '3.8.6'
      - name: Build with Maven
        run: mvn clean package

      - name: List build directory
        run: ls -la target
