name: apieliminatorias pipeline
on:
  push:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
      - ./Dockerfile
  pull_request:
    branches: [master]
    paths:
      - 'src/**'
      - '.github/workflows/main.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL_PROD: ${{ secrets.DB_URL_PROD }}
      DB_USER_PROD: ${{ secrets.DB_USER_PROD }}
      DB_PASS_PROD: ${{ secrets.DB_PASS_PROD }}
      SECRET_KEY_FUT: ${{ secrets.SECRET_KEY_FUT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Maven build
        run: mvn --batch-mode --update-snapshots clean package

      - name: Upload JAR file
        uses: actions/upload-artifact@v3
        with:
          name: apieliminatoria
          path: target/apiEliminatorias-0.0.1-SNAPSHOT.jar

  Build-docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download JAR file
        uses: actions/download-artifact@v3
        with:
          name: apieliminatoria
          path: target/

      - name: List files
        run: ls -la

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: luisvill/apieliminatoria:latest
          context: .
          file: Dockerfile
